plugins: [babel, jest]
env:
  node: true
  es6: true
  jest: true

extends: 
  - 'eslint:recommended'
  - 'airbnb-base'

parserOptions:
  ecmaVersion: 2018
  sourceType: module

rules: {
  no-console: 'off',
}
