url: ".*kitchenaid.com\/.*\/(cart|checkout).*"
total: 89
orderTotal: 76
season: 'Summer'
product:
  year: 2019
  models:
    air:
      price: 190000
    pro:
      price: 150000
      discount: true
      best-price: true
  options:
    option1: 'four'
    option2: 'four'
    option3: 'four'
