url: ".*kitchenaid.com\/.*\/(cart|checkout).*"
total: 8979
orderTotal: 789876
product:
  productName: 'Apple MacBook'
  year: 2019
  cashback: false
  models:
    air:
      price: 190000
    pro:
      price: 290000
  options:
    option1: 'one'
    option2: 'two'
